Стилизация главной страницы
htmlacademy-adaptive/223497-cat-energy-22 pull request #7
Opened 2021-04-03 23:28 UTC by lapskaya-ks

У меня есть вопрос :) Во-первых, насколько все плохо? Во-вторых, у меня есть некоторые проблемы. Так, например, я не до конца поняла, как сделать раздел "selection", там все не очень хорошо. Плюс в секции "how-works" я запуталась с псевдоэлементами. Этот раздел нужно повторить однозначно. 

В общем, буду ждать от тебя итог!

2021-04-04 12:15 UTC, SidSpears69 requested changes

2021-04-04 12:15 UTC, SidSpears69 commented on source/form.html
> +    <link href="/css/style.css" rel="stylesheet">
Перед css слэш не нужен

2021-04-04 12:15 UTC, SidSpears69 commented on source/sass/blocks/programs.scss
> +  font-family: "Oswald", "Arial", sans-serif;
Дублирование шрифтов для каждого элемента излишне, достаточно задать для всего документа и менять по мере необходимости

2021-04-04 12:15 UTC, SidSpears69 commented on source/sass/global/global.scss
> +ul {
Нарушение критерия д16, там как раз ul и p приведены как пример недопустимости стилизации глобальных тегов

2021-04-04 17:49 UTC, lapskaya-ks commented on source/sass/blocks/example.scss
> +.example__stats-list {
Здесь я не делала отдельный блок, потому что он не может просто существовать на сайте (по логике относится к блоку example, просто задала другие имена)

2021-04-04 17:50 UTC, lapskaya-ks commented on source/sass/blocks/how-works.scss
> +.how-works__description--benefit::before {
Пока с модификаторами повременю, не до конца работают псевдоэлементы, не хочу составлять пока заведомо неверную конструкцию.

2021-04-04 17:51 UTC, lapskaya-ks commented on source/sass/blocks/programs.scss
> +  font-family: "Oswald", "Arial", sans-serif;
Кое-где я удалила дублирование, но в некоторых местах пришлось вернуть, потому что не срабатывало.

2021-04-04 17:51 UTC, lapskaya-ks commented on source/sass/global/global.scss
> +ul {
Убрала

2021-04-04 22:46 UTC, SidSpears69 commented on source/sass/blocks/how-works.scss
> +.how-works__description--benefit::before {
"Не до конца работают псевдоэлементы" - что конкретно им мешает работать "до конца"?)

2021-04-04 22:46 UTC, SidSpears69 commented on source/sass/blocks/programs.scss
> +  font-family: "Oswald", "Arial", sans-serif;
В данном случае, ты задаешь шрифты для ссылки и ее состояний, при смене состояния шрифт не должен меняться, 
стили для псевдокласса link одинаковые со стилями элемента без состояний, думаю, использование псевдокласса link излишне, hover, focus, лучше задавать только для десктопных версий, на мобильных нет понятия наведения, а фокус иногда вызывает баги

2021-04-04 22:46 UTC, SidSpears69 commented on source/form.html
> +    <link href="/css/style.css" rel="stylesheet">
Дублирую правку, это важно

2021-04-04 22:47 UTC, merged

2021-04-05 13:39 UTC, lapskaya-ks commented on source/sass/blocks/programs.scss
> +  font-family: "Oswald", "Arial", sans-serif;
Точно, я действительно не подумала, что это мобильная версия и задавать состояние не нужно.

2021-04-05 13:41 UTC, lapskaya-ks commented on source/form.html
> +    <link href="/css/style.css" rel="stylesheet">
Странно, что ты видишь со /, я его убрала.

2021-04-05 20:50 UTC, lapskaya-ks commented on source/sass/blocks/how-works.scss
> +.how-works__description--benefit::before {
Мне нужно до конца с ними разобраться, вот что)